# Generated by Django 3.1 on 2023-05-30 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('sexo', models.IntegerField(choices=[[1, 'Hombre'], [2, 'Mujer'], [3, 'No Binario']])),
                ('edad', models.IntegerField()),
                ('especialidad', models.CharField(max_length=50)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=30)),
                ('hora', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.paciente')),
            ],
        ),
    ]
